INSERT INTO Products (Category, Name, Price, UrlImg, Description)
VALUES
    ('roller', 'Rainbow Five', 99.95, 'https://img.freepik.com/free-photo/cool-roller-skate-still-life_23-2150304799.jpg?t=st=1687778130~exp=1687778730~hmac=241b2465aa354253729ebfd64ce065b2c5f8d329e07fa8a3784ef3ca49f52e52&w=740', 'Experience the vibrant joy of skating with our Rainbow Five roller skates. These sleek and stylish skates feature a colorful design that will make you stand out on the rink. With smooth-rolling wheels and a comfortable fit, these skates are perfect for beginners and experienced skaters alike. Let the rainbow guide your every glide!'),
    ('roller', 'Rainbow Six', 119.95, 'https://img.freepik.com/free-photo/cool-roller-skate-still-life_23-2150304807.jpg?t=st=1687772830~exp=1687773430~hmac=987166a4afcbe72f190a078bd4ff7f9a03a5a025041a361ce2ae9c1e00435598&w=740', 'Take your skating game to the next level with our Rainbow Six roller skates. These high-performance skates combine style and functionality for an unforgettable skating experience. The eye-catching rainbow design will turn heads as you zoom by, while ensuring a smooth ride and comfortable fit. Get ready to shine on the rink with Rainbow Six.'),

    ('roller', 'Pink Future', 132.95, 'https://img.freepik.com/free-photo/cool-roller-skate-still-life_23-2150304791.jpg?t=st=1687772878~exp=1687773478~hmac=ab016b44dddeb854d4e4b0c5ccda4dd473c7fe40c6c64ba3da6485f16679b572&w=740', 'Step into the future of skating with our Pink Future roller skates. These cutting-edge skates not only deliver a sleek and stylish look but also provide superior performance. The pink color exudes confidence and dynamism, while offering stability and control. Embrace the future of skating and make a bold statement on the rink.'),

    ('roller', 'Purple Future', 159.99, 'https://img.freepik.com/free-photo/cool-roller-skate-still-life_23-2150304795.jpg?t=st=1687772953~exp=1687773553~hmac=8d26c5da92d5c2c656613bd44a485387f18006168f64c861c845c267fac656ee&w=740', 'Unleash your inner skater with our Purple Future roller skates. Designed for those who crave both style and performance, these skates feature a stunning purple color that will make you the center of attention. With a smooth ride and durable construction, these skates are built to last. Get ready to skate into the future with Purple Future.'),

    ('roller', 'Blue classic', 99.99, 'https://img.freepik.com/free-photo/cool-roller-skate-still-life_23-2150304805.jpg?t=st=1687773119~exp=1687773719~hmac=f0bba25cb1566af0070e23d5860e4d3714be0603c64e13d9fbf8a1e86c343c27&w=740', 'Rediscover the timeless charm of skating with our Blue Classic roller skates. These skates embrace the nostalgia of classic roller skating with a modern twist. The sleek blue design adds a touch of elegance, while providing stability and maneuverability on the rink. Whether you are a seasoned skater or a beginner, these skates will bring joy to your every stride.'),

    ('roller', 'Cream Classic', 89.95, 'https://img.freepik.com/free-photo/cool-roller-skate-still-life_23-2150304814.jpg?t=st=1687773185~exp=1687773785~hmac=0a8867a1d7398dc826aed29a7a88a8e5ab2a04692d8d710df466bf56dc71581b&w=740', 'Experience the epitome of elegance with our Cream Classic roller skates. These skates combine a vintage aesthetic with modern comfort, creating a perfect blend of style and functionality. The creamy color exudes sophistication, while ensuring a smooth and enjoyable ride. Step into these skates and let your inner grace shine on the rink.'),

	('skate', 'Legacy Bird', 68.99, 'https://img.freepik.com/premium-photo/pair-skateboards-with-black-crow-front_900370-12480.jpg?w=826', 'Experience timeless appeal and optimal performance with our Retro Cruiser skateboard. The sleek black color and iconic crow graphic give it a distinctive look. Whether youre a beginner or a seasoned rider, this skateboard guarantees a smooth and enjoyable experience. Carve your own path with style.'),

	('skate', 'Stormtrooper Helmet', 99.95, 'https://img.freepik.com/premium-photo/two-skateboards-with-one-that-has-storm-trooper-it_900370-12467.jpg?w=740', 'Unleash the force of style with our Galactic Rider skateboard. Inspired by the legendary Stormtrooper helmet, this skateboard features a sleek black and white design with an iconic graphic. Join the ranks of the skateboarding elite and showcase your individuality with this extraordinary skateboard!'),

	('skate', 'Skull Mex Skate', 89.95, 'https://img.freepik.com/premium-photo/two-skateboards-with-skulls-them-one-which-has-skull-it_900370-12483.jpg?w=740', 'Dominate the streets with Mexican flow. Embrace the rebellious spirit and unleash your inner strength with this edgy ride. The captivating skull graphic adds a touch of attitude. Whether grinding rails or mastering tricks, the Skull will accompany you on your journey to skateboarding greatness.'),

	('skate', 'Ghibli Style', 59.95, 'https://img.freepik.com/premium-photo/two-skateboards-with-picture-giant-monster-bottom_900370-12466.jpg?w=740', 'Embark on an anime-inspired adventure with our Anime Cruiser skateboard. Featuring captivating artwork and vibrant colors, this skateboard brings the magic of Ghibli films to life. With its smooth ride and sturdy construction, its perfect for both beginners and anime enthusiasts. Let your imagination soar with this eye-catching skateboard.'),

	('skate', 'Dragon Ball Flip', 79.95, 'https://img.freepik.com/premium-photo/skateboard-with-cartoon-image-woman-with-green-hair_900370-12470.jpg?w=740', 'Unleash your inner power with our Super Saiyan Shredder skateboard. Featuring a captivating design inspired by anime, this skateboard is perfect for expressing your style. Whether youre cruising or performing tricks, it delivers an exceptional ride. Embrace the energy and stand out from the crowd with this powerful skateboard'),

	('skate', 'Skull Rider', 79.95, 'https://img.freepik.com/fotos-premium/resumen-risografia-liquido-burbujeante-flotando-superficie_1279815-119467.jpg?w=826', 'Stand out with the Skull Rider skateboard. Features vibrant skull artwork and top-quality build.'),

	('skate', 'Ghostly Shred', 84.95, 'https://img.freepik.com/fotos-premium/resumen-risografia-liquido-burbujeante-flotando-superficie_1279815-119448.jpg?w=826', 'Shred in style with the Ghostly Shred skateboard. Colorful skull design and durable construction.'),

	('skate', 'Skull Thrill', 89.95, 'https://img.freepik.com/fotos-premium/articulo-colorido-craneo-el-sienta-mesa_1279815-119739.jpg?w=826', 'Experience the Skull Thrill skateboard. Bold skull graphics and superior quality.'),

	('surfskate', 'Black PantherY', 129.95, 'https://yowsurf.com/wp-content/uploads/yow-medina-panthera-33.5-surfskate-bottom-scaled.jpg', 'Discover the vibrant world of surf skating with our Colorful Stars board. Its eye-catching design features a burst of colorful stars that will turn heads as you ride. Experience the perfect combination of style and performance, allowing you to carve and cruise with ease. Get ready to shine on the streets and elevate your surf skating game with this captivating board!'),

	('surfskate', 'Classic Wood', 139.95, 'https://yowsurf.com/wp-content/uploads/yow-lowers-34-surfskate-bottom.jpg', 'Embrace the captivating world of surf skating with our Colorful Geometry board. Its dynamic geometric pattern adds a modern touch to your ride, while providing a stable and responsive experience. The high-quality construction ensures durability and smooth gliding. Unleash your creativity and conquer the streets with this stunning board that combines style and functionality!'),

	('surfskate', 'Beginners Enthusiasm', 110.95, 'https://yowsurf.com/wp-content/uploads/yow-grom-mundaka-32-surfskate-bottom-2.jpg', 'Experience the joy of surf skating with our Colorful Dots board. Its playful design features a vibrant array of dots that will bring energy to your rides. The boards smooth performance and responsive handling make it a perfect choice for riders of all levels. Stand out from the crowd and express your individuality with this fun and reliable surf skate!'),

	('surfskate', 'Begginers Luck', 89.95, 'https://yowsurf.com/wp-content/uploads/yow-coxos-31-surfskate-bottom-2.jpg', 'Ride with confidence and style on our Green Hexagons surf skate. Its captivating design features a pattern of green hexagons that exudes a modern and fresh vibe. With its smooth gliding and responsive maneuverability, this board allows you to explore new tricks and techniques. Let your true colors shine.'),

	('surfskate', 'Blue Skull Surfskate', 139.95, 'https://yowsurf.com/cdn/shop/files/christenson-lane-splitter-34_complete-surfskate-01.jpg?v=1716297497', 'Ride with style on the Blue Skull Surfskate. Features a vibrant blue skull design and excellent quality.'),

	('surfskate', 'Red Skull Surfskate', 144.95, 'https://www.delocossurfshop.com/wp-content/uploads/2023/06/yow-x-christenson-skalle-34-surfskate-bottom-scaled-1.jpg', 'Shred the streets with the Red Skull Surfskate. Boasts a striking red skull design and superior build.'),

	('surfskate', 'Marine Wood Longboard', 159.95, 'https://yowsurf.com/cdn/shop/files/calmon-41_-complete-surfskate-01.jpg?v=1716297550', 'Enjoy a smooth ride on the Marine Wood Longboard Surfskate. Combines a classic wood style with marine motifs for a unique look and quality performance.'),

	('other', 'Basic Toolbox', 39.95, 'https://img.freepik.com/premium-photo/toolbox-set-with-everything-you-need-any-job_829136-808.jpg?w=826', 'Maintain and repair your roller skates, skateboards, and surfskates with ease using our comprehensive toolbox set. It includes a wide range of essential tools for adjustments, repairs, and maintenance. Whether youre a beginner or a pro skater, this set provides everything you need to keep your gear in optimal condition and ensure flawless performance during every session. Get ready for worry-free skating.'),

	('other', 'Premium Toolbox', 55.95, 'https://img.freepik.com/premium-photo/toolbox-with-everything-you-need-any-job_829136-799.jpg?w=826', 'Take your maintenance and repair game to the next level with our premium toolbox set. Designed for the most discerning enthusiasts, this set offers high-quality tools that guarantee durability and precision for every adjustment and repair. From heavy-duty wrenches and screwdrivers to specialized tools for bearings and axles, this comprehensive kit provides everything you need.');
